# Generated by Django 2.2.5 on 2021-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('product', models.CharField(default=' ', max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('READY TO DISTRIBUTE', 'Item ready to be distributed'), ('DISTRIBUTED', 'Item already distributed'), ('NEEDS RESTOCKING', 'Item needs restocking')], default=' ', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kitchenware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('product', models.CharField(default=' ', max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('READY TO DISTRIBUTE', 'Item ready to be distributed'), ('DISTRIBUTED', 'Item already distributed'), ('NEEDS RESTOCKING', 'Item needs restocking')], default=' ', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
